=== willipedsu/TercerCorte/Taller 2 validacion XML/TallerXML/bin/NewDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT estudiante (codigo,nombre,semestre+)>
<!ELEMENT codigo (#PCDATA) >
<!ELEMENT nombre (#PCDATA) >
<!ELEMENT semestre (anos, cursos+)>
<!ELEMENT anos (#PCDATA) >
<!ELEMENT cursos (nota1,nota2,nota3,notaFinal) >
<!ELEMENT nota1 (#PCDATA)>
<!ELEMENT nota2 (#PCDATA)>
<!ELEMENT nota3 (#PCDATA)>
<!ELEMENT notaFinal (#PCDATA)>

=== willipedsu/TercerCorte/Taller 2 validacion XML eclipse/TallerXML/bin/FileXML2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE estudiante SYSTEM "NewDTD.dtd" >
<estudiante>
  <codigo>codigo</codigo>
  <nombre>nombre</nombre>
  <semestre>
    <anos>anos</anos>
    <cursos>
      <nota1>nota1</nota1>
      <nota2>nota2</nota2>
      <nota3>nota3</nota3>
      <notaFinal>notaFinal</notaFinal>
    </cursos>
  </semestre>
</estudiante>
